kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: hello-app-allow
spec:
  podSelector:
    matchLabels:
      run: hello-app
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: nginx-ingress